language: julia
os:
- linux
julia:
- 1.0
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
  - downloads
env:
  global:
  - BINARYBUILDER_DOWNLOADS_CACHE=downloads
  - BINARYBUILDER_AUTOMATIC_APPLE=false
  # Our build takes too long for one job, so split targets across multiple jobs
  # triplets come from using BinaryBuilder; triplet.(supported_platforms())
  # matrix:
  #   - TARGET=i686-linux-gnu
  #   - TARGET=x86_64-linux-gnu
  #   - TARGET=aarch64-linux-gnu
  #   - TARGET=arm-linux-gnueabihf
  #   - TARGET=powerpc64le-linux-gnu
  #   - TARGET=i686-linux-musl
  #   - TARGET=x86_64-linux-musl
  #   - TARGET=aarch64-linux-musl
  #   - TARGET=arm-linux-musleabihf
  #   - TARGET=x86_64-apple-darwin14
  #   - TARGET=x86_64-unknown-freebsd11.1
  #   - TARGET=i686-w64-mingw32
  #   - TARGET=x86_64-w64-mingw32
sudo: required
jobs:
  include:
    - stage: regenerate build.jl
      script: julia --color=yes build_tarballs.jl --only-buildjl
      if: tag IS present
before_script:
- julia --color=yes -e 'using Pkg; pkg"add BinaryProvider"; pkg"add BinaryBuilder#master"; Pkg.build()'
script:
- julia --color=yes build_tarballs.jl
deploy:
  provider: releases
  api_key:
    secure: uJNmBarJGHng/UK2SR84lvVOM0BLLqMALO/P8e/JPz2XI4bOonL9u/noqRl03B0hXOHfzQeCQjR+6Im1usNbVnClixz6XWa6yqfQyVYp2vtWtBzHPHE3vNHolwZ0VOpms1k2wRZ8Na9+Efv3MjDWpuxbQIMLvpYx7bZ0NBRyJKUZZcOIzrcbPrtqrhCfPMHde2U9mebVwbxE2m3vDibUY+7BAeVhWo5fB6TZzBBxARosZr1efEb5z/jItVAlsx+o0IDcIn9PeWiQWA0LkBzoaT0Rn9CY3a9PspSBg2iK9qUd/ayKs85y9o4rEKOP+ct4qG4li6sMg5bqz5CNaGUR2/T+8IOx/SR3dLUQG4YxUYIp9xBHRgC9YPt8tQb7bTwmem3OOP9r0wLr9YVGptYIF90I4i13jfSMmJu6jn3F9hrVhgqCJdZo1NnAqTEpat+CHyYO43j/4Fh2Bvtu9bljWDmM6snLrMZChNsCxqS6bW2NYUvqM9Kl3cAOWIWicRflj35vNmDTXrMWSvCPgCK0NWl+YcIVGLrMKkdyPrxu7ZKtGfXdCLeYYluOV4qoNgB4kP+c/8n0yf9yM6YP4IF3ACxaaShHQW5I8hzmGnrRU8345U4x72iaNiKeAvMhz8hoGCMgGBBAfhBlzaAabhTLF9wiLng8WJT4vqAeEOYuQg8=
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: JoshChristie/CutPursuitBuilder
    tags: true
